<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403235414 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, position INT NOT NULL, code_example TEXT DEFAULT NULL, tutorial_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43B9FE3C89366B7B ON step (tutorial_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE step ADD CONSTRAINT FK_43B9FE3C89366B7B FOREIGN KEY (tutorial_id) REFERENCES tutorial (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tutorial ADD description TEXT NOT NULL');
        $this->addSql('ALTER TABLE tutorial ADD status VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE tutorial ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE tutorial ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE tutorial ADD rejection_reason TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE tutorial ADD category VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE tutorial ADD author_id INT NOT NULL');
        $this->addSql('ALTER TABLE tutorial RENAME COLUMN tutorial TO title');
        $this->addSql('ALTER TABLE tutorial ADD CONSTRAINT FK_C66BFFE9F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C66BFFE9F675F31B ON tutorial (author_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE step DROP CONSTRAINT FK_43B9FE3C89366B7B');
        $this->addSql('DROP TABLE step');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE tutorial DROP CONSTRAINT FK_C66BFFE9F675F31B');
        $this->addSql('DROP INDEX IDX_C66BFFE9F675F31B');
        $this->addSql('ALTER TABLE tutorial DROP description');
        $this->addSql('ALTER TABLE tutorial DROP status');
        $this->addSql('ALTER TABLE tutorial DROP created_at');
        $this->addSql('ALTER TABLE tutorial DROP updated_at');
        $this->addSql('ALTER TABLE tutorial DROP rejection_reason');
        $this->addSql('ALTER TABLE tutorial DROP category');
        $this->addSql('ALTER TABLE tutorial DROP author_id');
        $this->addSql('ALTER TABLE tutorial RENAME COLUMN title TO tutorial');
    }
}
